### ISSUE TITLE
Is there any plan to support Apache Maven?

### ISSUE THREAD

**Issue by hoyeol** [mattupstate/spring-social-foursquare#5]
I saw you using gradle.

but just i think still many people using apache maven too.
(if apache maven user want to using this on there environment, they must do like this. 
1. download sourcecode
2. open there gradle file to understanding which library using
3. make project with pom file with dependencies, copy source code to there project.
it's too boring work! )

if support apache maven, i think it's helpful to using better who still using apache maven.

it just my suggestion, if don't like this. just skip this suggestion.

**Comment by mattupstate** [comment]
The reason I'm using gradle is because SpringSource is using gradle for the build system. Unfortunately spring-social-foursquare isn't being distributed to any official maven repositories yet. I haven't had much time to explore doing this. For the time being, though, I'm posting an archive of the the build artifacts (jar files) in the [downloads](https://github.com/mattupstate/spring-social-foursquare/downloads) area. 

If you'd like to use maven, you'll need to clone this repository, and install the library into your local maven repository by running:

```
$ ./gradlew install
```

You can then use maven. The [example project](https://github.com/mattupstate/spring-social-foursquare-example) should give you an idea how to do this:

**Comment by jramsdale** [comment]
Here's info on how to deploy artifacts to Sonatype OSS (automatically synced to Maven Central) via Gradle: http://jedicoder.blogspot.com/2011/11/automated-gradle-project-deployment-to.html

Here's an example: https://github.com/GradleFx/GradleFx/blob/master/build.gradle

Here's more info on Sonatype OSS, which is free for open source projects: https://docs.sonatype.org/display/Repository/Sonatype+OSS+Maven+Repository+Usage+Guide

Hope that helps!
